### ISSUE TITLE
Question - Compatibility with uDropship

### ISSUE THREAD

**Issue by franciskim** [Go-Shippit/Magento2#1]
Hi guys, my client uses a dropshipping module for Magento 2 called uDropship from Unirgy, it's one of the more well-known ones. Any idea if this module would be compatible with it? I believe uDropship does override the pick up location depending on the location of the warehouse/vendor (it's actually a multi-vendor marketplace that I'm building). Any insight would be much appreciated!

**Comment by matthew-muscat** [comment]
Hi @franciskim,

Sorry for the delay in response - GitHub issues aren't actively monitored at this time...

The module should operate as intended, however you may need build out some logic with regards to determining when an order is to be sent to Shippit and, if required, to which account in Shippit

To summarise, the module provides functionality with regards to sending orders to Shippit, as well as live quoting.

Assuming your question is with regards to sending orders..

a) Orders / Order items from Vendors "A" and "B" to be sent to Shippit Account "X"
b) Orders from Vendors "C", "D" to be sent to Shippit Account "Y"
c) Orders from Vendors "E" and "F" to not be sent to Shippit

(i've assumed different accounts since they are different warehouses / vendors and each warehouse / vendor only requires visibility of their applicable orders)

This behaviour may be best implemented via a custom integration method, whereby you trigger events that we consume in our observer (https://github.com/Go-Shippit/Magento2/blob/master/Observer/Shippit.php) - you can also specify the skus to be included in the order in cases where an order is split amongst multiple vendors.

I'd suggest reaching out to us via apps@shippit.com and mention myself or Peter Oh.
