### ISSUE TITLE
Shippit

### ISSUE THREAD

**Issue by davids123** [Go-Shippit/Magento2#10]
cart page is not showing shippit until I go checkout and then come again

**Comment by matthew-muscat** [comment]
Hi @davids123,

Shippit Live quotes should appear if you fill in the "Shipping Estimator" on the cart page — you'll need to ensure that a valid postcode and suburb is submitted in the "Shipping Estimator", otherwise, the quote may fail to go through.

Note: the module wil ensure the suburb + postcode field is displayed on the cart's "Shipping Estimator" — although if you have customisations to this area in the frontend, it's possible it won't be displayed.

Can you please email apps@shippit.com with some details as to what you are seeing?
