### ISSUE TITLE
Magento 2.1.5 Shippit not working with default billing and shipping address

### ISSUE THREAD

**Issue by syedsaleem086** [Go-Shippit/Magento2#2]
Hi,

Shippit is only working for customers who don't have the saved address.

We have installed this module using composer.
Hope you can reproduce this issue on
PHP 7.0
Magento 2.1.5

**Comment by matthew-muscat** [comment]
Hi @syedsaleem086,

We've seen an issue that might be related to what you have described — this was causing live quotes to not appear in the checkout when using saved addresses.

This was due to a Magento core bug that was subsequently fixed in a later release.

If you are still encountering the issue, could you please provide more details as to what you are experiencing? Are live quotes not appearing in your case?

**Comment by syedsaleem086** [comment]
Hi @matthew-muscat 
We changed Magento core to fix this thanks

**Comment by matthew-muscat** [comment]
Thanks @syedsaleem086 — closing this one out.
